-- liquibase formatted sql

-- changeset klikli:1
CREATE TABLE dog
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name          TEXT NOT NULL,
    age           INTEGER NOT NULL ,
    breed         TEXT NOT NULL
);

CREATE TABLE owner_dog
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    chat_id       BIGINT NOT NULL,
    name          TEXT NOT NULL,
    phone         TEXT NOT NULL,
    age           INTEGER NOT NULL,
    dog_id        BIGINT REFERENCES dog(id)
);

CREATE TABLE shelter
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name          TEXT NOT NULL,
    address       TEXT NOT NULL,
    mail          TEXT NOT NULL,
    phone         TEXT NOT NULL,
    opening_hours TIMESTAMP NOT NULL,
    map           BYTEA
);

-- changeset klikli:2

ALTER TABLE owner_dog ADD COLUMN status TEXT;

ALTER TABLE dog ADD COLUMN status TEXT;

-- changeset klikli:3

ALTER TABLE owner_dog ALTER COLUMN status SET  DEFAULT 'IN_SEARCH';

ALTER TABLE dog ALTER COLUMN status SET DEFAULT 'FREE';

-- changeset klikli:4

ALTER TABLE owner_dog ALTER COLUMN age DROP NOT NULL;

ALTER TABLE shelter ALTER COLUMN opening_hours TYPE TEXT;

-- changeset MarinaGubina:1
CREATE TABLE report
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY ,
    photo           BYTEA ,
    animal_diet     TEXT NOT NULL ,
    general_info    TEXT NOT NULL ,
    change_behavior TEXT NOT NULL ,
    status          TEXT DEFAULT 'REPORT_POSTED'
);
